# Generated by Django 4.0.5 on 2022-06-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.TextField()),
                ('librarian', models.CharField(max_length=255)),
                ('student', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('borrowed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
