# Generated by Django 4.0.6 on 2022-08-18 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='borrowers',
            field=models.ManyToManyField(blank=True, related_name='borrowers', to=settings.AUTH_USER_MODEL),
        ),
    ]
