# Generated by Django 4.0.5 on 2022-07-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='book',
            new_name='bookCategory',
        ),
    ]
