# Generated by Django 4.0.5 on 2022-07-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_book_bookshelf_bookcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='base/covers'),
        ),
    ]
