# Generated by Django 4.0.5 on 2022-06-11 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_subject_remove_bookshelf_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('borrowdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrowed',
        ),
        migrations.RemoveField(
            model_name='book',
            name='student',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded',
        ),
        migrations.RemoveField(
            model_name='bookshelf',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='bookshelf',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='borrowstatus',
            name='bookshelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bookshelf'),
        ),
        migrations.AddField(
            model_name='borrowstatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
