# Generated by Django 4.0.6 on 2022-08-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_borrow_delete_borrower_alter_bookshelf_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='borrowers',
        ),
    ]
