# Generated by Django 4.0.5 on 2022-07-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_book_cover_bookshelf_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
