# Generated by Django 4.0.5 on 2022-07-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_bookshelf_description_alter_bookshelf_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='cover',
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='book_image_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
