# Generated by Django 4.0.6 on 2022-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_bookshelf_cover_bookshelf_book_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='book_image_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='borrowstatus',
            name='borrowdate',
            field=models.DateTimeField(max_length=100),
        ),
    ]
